services:
  # === WEB SERVERS ===
  web1:
    build: ./web-servers
    container_name: web1
    hostname: web1
    networks:
      - app-network

  web2:
    build: ./web-servers
    container_name: web2
    hostname: web2
    networks:
      - app-network

  # === HIGH-AVAILABILITY LOAD BALANCERS ===
  haproxy-master:
    build: ./haproxy-master
    container_name: haproxy-master
    # Exposes the main application entrypoint on the host's port 80.
    ports:
      - "80:80"
    # Grants the container extra capabilities required by Keepalived to manage network interfaces and the Virtual IP.
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - app-network
    # Ensures the tier-2 load balancers are started before this one.
    depends_on:
      web1: { condition: service_started }
      web2: { condition: service_started }

  haproxy-backup-1:
    build: ./haproxy-backup-1
    container_name: haproxy-backup-1
    ports:
      # Expose the backup's stats page on a different host port for debugging.
      - "8080:80"
    # Grants the container extra capabilities required by Keepalived.
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - app-network
    # Ensures the tier-2 load balancers are started before this one.
    depends_on:
      web1: { condition: service_started }
      web2: { condition: service_started }

  haproxy-backup-2:
    build: ./haproxy-backup-2
    container_name: haproxy-backup-2
    ports:
      # Expose the backup's stats page on a different host port for debugging.
      - "8081:80"
    # Grants the container extra capabilities required by Keepalived.
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - app-network
    # Ensures the tier-2 load balancers are started before this one.
    depends_on:
      web1: { condition: service_started }
      web2: { condition: service_started }

networks:
  app-network:
    driver: bridge
    # IP Address Management (IPAM) configures the private network for our containers.
    ipam:
      driver: default
      config:
        # Defines a specific subnet, allowing us to have predictable internal IP addresses.
        - subnet: 192.168.100.0/24
