services:
  # === WEB SERVERS (TIER 3) ===
  web1:
    build: ./web-servers
    container_name: web1
    hostname: web1
    networks:
      - app-network

  web2:
    build: ./web-servers
    container_name: web2
    hostname: web2
    networks:
      - app-network

  web3:
    build: ./web-servers
    container_name: web3
    hostname: web3
    networks:
      - app-network

  # === APPLICATION LOAD BALANCERS (TIER 2) ===
  haproxy-tier2-1:
    build: ./haproxy-tier2-1
    container_name: haproxy-tier2-1
    ports:
      - "8081:80"
    networks:
      - app-network
    # Ensures web servers are started before this load balancer tries to connect to them.
    depends_on:
      web1: { condition: service_started }
      web2: { condition: service_started }
      web3: { condition: service_started }

  haproxy-tier2-2:
    build: ./haproxy-tier2-2
    container_name: haproxy-tier2-2
    ports:
      - "8082:80"
    networks:
      - app-network
    # Ensures web servers are started before this load balancer tries to connect to them.
    depends_on:
      web1: { condition: service_started }
      web2: { condition: service_started }
      web3: { condition: service_started }

  # === HIGH-AVAILABILITY LOAD BALANCERS (TIER 1) ===
  haproxy-tier1-master:
    build: ./haproxy-tier1-master
    container_name: haproxy-tier1-master
    # Exposes the main application entrypoint on the host's port 80.
    ports:
      - "80:80"
    # Grants the container extra capabilities required by Keepalived to manage network interfaces and the Virtual IP.
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - app-network
    # Ensures the tier-2 load balancers are started before this one.
    depends_on:
      haproxy-tier2-1: { condition: service_started }
      haproxy-tier2-2: { condition: service_started }

  haproxy-tier1-backup:
    build: ./haproxy-tier1-backup
    container_name: haproxy-tier1-backup
    ports:
      # Expose the backup's stats page on a different host port for debugging.
      - "8080:80"
    # Grants the container extra capabilities required by Keepalived.
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - app-network
    # Ensures the tier-2 load balancers are started before this one.
    depends_on:
      haproxy-tier2-1: { condition: service_started }
      haproxy-tier2-2: { condition: service_started }

networks:
  app-network:
    driver: bridge
    # IP Address Management (IPAM) configures the private network for our containers.
    ipam:
      driver: default
      config:
        # Defines a specific subnet, allowing us to have predictable internal IP addresses.
        - subnet: 192.168.100.0/24
